Update load_tool.py
Fix for issue that causes the following error
File "/usr/local/lib/python3.5/dist-packages/scriptcwl/scriptcwl.py", line 30, in <module>
from cwltool.load_tool import fetch_document, validate_document
ImportError: cannot import name 'validate_document'